export const instrumentList = [
  { name: 'Acoustic Grand Piano', program: 0 },
  { name: 'Church Organ', program: 19 },
  { name: 'Reed Organ', program: 20 },
  { name: 'Harmonica', program: 22 },
  { name: 'Acoustic Guitar (nylon)', program: 24 },
  { name: 'Acoustic Bass', program: 32 },
  { name: 'Violin', program: 40 },
  { name: 'Viola', program: 41 },
  { name: 'Cello', program: 42 },
  { name: 'Contrabass', program: 43 },
  { name: 'String Ensemble 1', program: 48 },
  { name: 'String Ensemble 2', program: 49 },
  { name: 'Choir Aahs', program: 52 },
  { name: 'Voice Oohs', program: 53 },
  { name: 'Oboe', program: 68 },
  { name: 'Flute', program: 73 },
  { name: 'Shakuhachi', program: 77 },
  { name: 'Whistle', program: 78 },
  { name: 'Ocarina', program: 79 },
]

export const SF_NAMES = [
  'acoustic_grand_piano','bright_acoustic_piano','electric_grand_piano',
  'honkytonk_piano','electric_piano_1','electric_piano_2','harpsichord','clavinet',
  'celesta','glockenspiel','music_box','vibraphone','marimba','xylophone',
  'tubular_bells','dulcimer',
  'drawbar_organ','percussive_organ','rock_organ','church_organ','reed_organ',
  'accordion','harmonica','tango_accordion',
  'acoustic_guitar_nylon','acoustic_guitar_steel','electric_guitar_jazz',
  'electric_guitar_clean','electric_guitar_muted','overdriven_guitar',
  'distortion_guitar','guitar_harmonics',
  'acoustic_bass','electric_bass_finger','electric_bass_pick','fretless_bass',
  'slap_bass_1','slap_bass_2','synth_bass_1','synth_bass_2',
  'violin','viola','cello','contrabass','tremolo_strings','pizzicato_strings',
  'orchestral_harp','timpani',
  'string_ensemble_1','string_ensemble_2','synth_strings_1','synth_strings_2',
  'choir_aahs','voice_oohs','synth_voice','orchestral_hit',
  'trumpet','trombone','tuba','muted_trumpet','french_horn','brass_section',
  'synth_brass_1','synth_brass_2',
  'soprano_sax','alto_sax','tenor_sax','baritone_sax',
  'oboe','english_horn','bassoon','clarinet',
  'piccolo','flute','recorder','pan_flute','blown_bottle','shakuhachi','whistle','ocarina',
  'lead_1_square','lead_2_sawtooth','lead_3_calliope','lead_4_chiff',
  'lead_5_charang','lead_6_voice','lead_7_fifths','lead_8_bass__lead',
  'pad_1_new_age','pad_2_warm','pad_3_polysynth','pad_4_choir',
  'pad_5_bowed','pad_6_metallic','pad_7_halo','pad_8_sweep',
  'fx_1_rain','fx_2_soundtrack','fx_3_crystal','fx_4_atmosphere',
  'fx_5_brightness','fx_6_goblins','fx_7_echoes','fx_8_scifi',
]

export function getSfName(program) {
  return SF_NAMES[program] || 'acoustic_grand_piano'
}
